---

#- name: Create custom scripts directory
  #file:
    #path:  "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}"
    #owner: root
    #group: root
    #mode:  0755
    #state: directory
  #tags: ['hostapd', 'hostapd-monitoring']

#- name: Install hostapd stations query cli file
  #template:
    #src:   hostapd_cli_stations.py.j2
    #dest:  "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/hostapd_cli_stations.py"
    #owner: root
    #group: root
    #mode:  0755
  #tags: ['hostapd', 'hostapd-monitoring']

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-agent
    tasks_from: userparameter
  vars:
    zabbix_agent__userparameter:
      name: hostapd
      comment: Use hostapd_cli to interogate the hostapd service
      userparameters:
        - key: hostapd.discovery
          command: >
            /usr/bin/env python -c 'import json, sys; json.dump({"data": list(map(lambda x: {"{"+"#HOSTAPD_INSTANCE}": x}, {{ hostapd__instances.keys()|list|to_json}} ))}, sys.stdout)'
          comment: return zabbix discovery item for hostapd instances
        - key: hostapd.ping[*]
          command: >
            /usr/bin/env hostapd_cli -p{{ hostapd__instance_defaults.ctrl_interface|replace('%i', '$1') }} ping 2>/dev/null | grep -c PONG
          sudo: true
          sudo_group: '{{ hostapd__ctrl_interface_group }}'
          sudo_command: /usr/bin/env hostapd_cli -p[a-zA-Z-/.$]* ping
          comment: check if hostapd is alive
        #- key: hostapd.stations.count
          #command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/hostapd_cli_stations.py --count"
          #sudo: True
          #sudo_group: '{{ hostapd__ctrl_interface_group }}'
          #comment: 'get the current number of stations'
        #- key: hostapd.stations.discovery
          #command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/hostapd_cli_stations.py --discovery --zabbix"
          #sudo: True
          #sudo_group: '{{ hostapd__ctrl_interface_group }}'
          #comment: 'get all stations mibs in zabbix discovery format'
      state: present
  tags: ['hostapd', 'hostapd-monitoring']
