---

- name: Install hostapd default configuration file
  template:
    src:   hostapd.environment.j2
    dest:  '{{ hostapd__service_environment }}'
    owner: root
    group: root
    mode:  0644
  when: hostapd__service_environment is defined
  notify: [ 'restart-hostapd' ]
