---
# tasks file for hostapd

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['hostapd', 'hostapd-install']

- import_tasks: configure.yml
  tags: ['hostapd', 'hostapd-configure']

- import_tasks: service.yml
  tags: ['hostapd', 'hostapd-service']

- include_tasks: 'monitoring-{{ hostapd__monitoring }}.yml'
  when: hostapd__monitoring is defined
  tags: ['hostapd', 'hostapd-monitoring']

- include_tasks: facts.yml
  when: hostapd__facts|bool
  tags: ['hostapd', 'hostapd-facts']
