---

- name: install hostapd.service systemd unit file
  template:
    src:   hostapd.service.j2
    dest:  '/etc/systemd/system/{{ hostapd__service_name }}.service'
    owner: root
    group: root
    mode:  0755
  when: hostapd__service_configure_systemd|bool and ansible_service_mgr == 'systemd'
  register: _hostapd_service

- name: remove sysvinit unit file
  file:
    path:  /etc/init.d/hostapd
    state: absent
  when: hostapd__service_configure_systemd|bool and ansible_service_mgr == 'systemd'

- name: Reload systemd
  systemd:
    name:          '{{ hostapd__service_name }}'
    enabled:       yes
    daemon_reload: yes
  when: _hostapd_service|changed and ansible_service_mgr == 'systemd'

- name: Ensure hostapd is started and enabled on boot
  service:
    name:    '{{ hostapd__service_name }}'
    enabled: "{{ hostapd__service_enabled|bool }}"
    state:   "{{ hostapd__service_enabled|bool|ternary('started', 'stopped') }}"
