---

- name: Install hostapd.service systemd unit file
  template:
    src:   hostapd.service.j2
    dest:  "/etc/systemd/system/{{ hostapd__service_name|replace('%i', '') }}.service"
    owner: root
    group: root
    mode:  0755
  when: ansible_service_mgr == 'systemd' and hostapd__service_configure_systemd|bool
  register: _hostapd__service
  notify: [ 'restart-hostapd' ]

- name: Remove sysvinit unit file
  file:
    path:  /etc/init.d/hostapd
    state: absent
  when: ansible_service_mgr == 'systemd' and hostapd__service_configure_systemd|bool

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: _hostapd__service is changed and ansible_service_mgr == 'systemd'
